ALTER TABLE blob_state DROP COLUMN IF EXISTS initiate_gc_after;
ALTER TABLE blob_state DROP COLUMN IF EXISTS md5;
ALTER TABLE blob_state DROP COLUMN IF EXISTS sha256;
ALTER TABLE blob_state DROP COLUMN IF EXISTS size;
